### ISSUE TITLE
WordPress 4.9 nightly

### ISSUE THREAD

**Issue by tomusborne** [kallookoo/wp-color-picker-alpha#10]
This script no longer seems to be working on WP 4.9-alpha-41335.

The color pickers don't show (regular or alpha), and these errors appear when you click an area where the picker should show up: https://www.screencast.com/t/A6FdI4sQM

This is happening inside a meta box. Works great in 4.8.1, and works fine if the alpha script is dequeued. 

Any thoughts?

Here's a test plugin so you can see the issue: https://tomusborne.com/dev/test-color-picker-meta-box.zip

**Comment by foreverpinetree** [comment]
Hello, have you figured out how to fix this issue?

**Comment by kallookoo** [comment]
hi,
I noticed that the wp-color-picker script has been modified, so it does not work, until it is not RC I will not update the script to not do double work, I hope you understand.

**Comment by tomusborne** [comment]
Sounds good. It does look like they'll be sticking with that version (they've cleaned it up considerably). Might be worth adding a check in there so this script is compatible with 4.8 and 4.9.

I haven't looked at the changes that much in detail, but it looks like the element variable changed? Should be easy enough to check.

Thanks for the script BTW, it's great.

**Comment by arielk** [comment]
Hi @kallookoo thanks for your amazing work.

FYI [WordPress 4.9 RC1](https://wordpress.org/news/2017/10/wordpress-4-9-release-candidate/) just released, please test your script with the new version.

Thanks again.

**Comment by foreverpinetree** [comment]
Hi, I have made some changes to try to fix this problem, and now it works (I only tested with 4.6.0, 4.8.3 and 4.9RC). Before the author fix it, maybe you can have a try :)
Here is the file: http://3theme.com/wp_assets/temp/wp-color-picker-alpha.js

**Comment by iceablemedia** [comment]
@qiuhuanjian thanks! Your modified version works fine on my end too (tested with WP 4.8.3 and 4.9RC1, which is good enough for me).
Why don't you open a pull request so @kallookoo can review it and consider merging?

**Comment by kallookoo** [comment]
New script is already!!!
