### ISSUE TITLE
WP 4.8.2 - possible issue?

### ISSUE THREAD

**Issue by kprovance** [kallookoo/wp-color-picker-alpha#11]
I just read that it looks like WP 4.9 might be an issue.  I wonder if the core team messed with something for 4.8, or at least the .2 revision.  Consider the screenshot:

![color-picker](https://user-images.githubusercontent.com/3412363/31324903-5fdcdf28-ac85-11e7-9dde-a1fb431d3bd9.png)

I am in the process of adding this script and it's ability (which is awesome, by the way, just to mention it)to Redux Framework (option panel for WordPress) and somewhere between 4.7 and now, this CSS issue has cropped up.  Looking at your sample screenshots and this one, it looks as if they have begun tinkering with the CSS, and the slider handles do NOT look the same.

I read in a previous thread you would rather not patch this library until the 4.9 final, which I understand.  If you could test for this in the process, that would be awesome.

I may take a day to go into your code and see if there is an easy fix.  I'll be glad to share it if one is found.

Cheers!

- Kev

**Comment by foreverpinetree** [comment]
I checked my site which is running 4.8.2 and everything is ok.

**Comment by kprovance** [comment]
Huh.  Weird.  I'll look into this.  Something must be off by like...a pixel.

If I change the style on the iris-alpha-slider class from 17.6856 to 16.6856. everything lines up again.

**Comment by kprovance** [comment]
Not an issue then?  ;)

**Comment by kallookoo** [comment]
I do not believe and have never had that problem.

**Comment by abdullah1908** [comment]
Hello kallookoo,

Hope you are doing great.

After updating WP to 4.9, my setting page is broken where I have included WP Color Picker Alpha :(

Could you please help me out regarding this so I can further proceed.

Thanks in advance for your help!

Regards,
Abdullah
WP Engineer

**Comment by kprovance** [comment]
Seen the last Git commit date?  Update is already there.  :)

**Comment by abdullah1908** [comment]
That's great 💯 

Thank you so much @kprovance 👍

**Comment by kprovance** [comment]
Cheers, mate!
