### ISSUE TITLE
Customizer color picker onclick

### ISSUE THREAD

**Issue by rushijagani** [kallookoo/wp-color-picker-alpha#12]
Hello,

Everything working fine in the previous Version: 1.2.2.
I have updated the Version: 2.0

As soon as I enqueue the color wp-color-picker-alpha.js, the customizer's color picker block is clickable to the entire row. As you can see in the below screenshot.
![customizer](https://user-images.githubusercontent.com/17968680/32646851-a2ac2446-c614-11e7-919e-d56295d8c274.gif)

Using WordPress 4.8.3.

**Comment by kallookoo** [comment]
please, send you code for testing and theme name, WordPress version

**Comment by kallookoo** [comment]
Please, check new version and comment...
