### ISSUE TITLE
Plugin Conflict

### ISSUE THREAD

**Issue by aliaghdam** [kallookoo/wp-color-picker-alpha#16]
Hi,
There is a js conflict with WP Mailster and it seems they have overridden or changed the Color in their codes and it creates error!

https://i.imgur.com/s3WAEKQ.png
https://i.imgur.com/V6aYBXc.png

**Comment by kallookoo** [comment]
I'm sorry, but the file admin-plugins.js does not exist in the [WP Mailster Free](https://wordpress.org/plugins/wp-mailster/) plugin version 1.5.5.0
I can not help you...
