### ISSUE TITLE
Changing color doesn't fire "change" or "input" events

### ISSUE THREAD

**Issue by buhlahkay** [kallookoo/wp-color-picker-alpha#17]
Changing the color via the palette doesn't fire events. Only way to fire the events is to type in the input.

**Comment by kallookoo** [comment]
Sorry, but the palette works well, what version of the script and WordPress do you use?

**Comment by buhlahkay** [comment]
script: 2.1.3
wp: 4.9.4

**Comment by buhlahkay** [comment]
oh I missed the arguments section. nevermind.
