### ISSUE TITLE
Selecting none transparent color should reset transparent slider

### ISSUE THREAD

**Issue by tmconnect** [kallookoo/wp-color-picker-alpha#18]
If the selected color is an RGBA color and you pick a color from the palette, the transparency slider didn't reset and you will get a RGBA color and not the HEX value from the palette.

This makes sense if I change the color over the color range, but not if I'm selecting an HEX color from the palette.

After selecting a HEX color from the palette the transparency slider should be reset to 1.

**Comment by kallookoo** [comment]
It is assumed that the color will be transparent, for this reason it is maintained. 
The data-reset-alpha option was created if it were the case that transparency was optional.
If you do not want to use this option, you can change it using the change function.
