### ISSUE TITLE
Bug with hue mode

### ISSUE THREAD

**Issue by vulinhpc** [kallookoo/wp-color-picker-alpha#26]
When I use color picker alpha script in customizer together with twentynineteen theme, it causing js bug. 
I found that the theme has hue color option:

	$wp_customize->add_control(
		new WP_Customize_Color_Control(
			$wp_customize,
			'primary_color_hue',
			array(
				'description' => __( 'Apply a custom color for buttons, links, featured images, etc.', 'twentynineteen' ),
				'section'     => 'colors',
				'mode'        => 'hue',
			)
		)
	);

http://prntscr.com/mvqlq4
and It seem bug when mode is hue(it works without 'mode' =>'hue')
// Create a color picker which only allows adjustments to the hue.
			if ( self.options.type === 'hue' ) {
				return self._createHueOnly();

			}
the bug come when return self._createHueOnly();

Please check,
Thank you!

**Comment by kallookoo** [comment]
Hi @vulinhpc 
It should work, it will not be because of what you mention #25

**Comment by kallookoo** [comment]
Closed, now it checks if it is valid and does nothing if it is not.
