### ISSUE TITLE
Problem in customizer "too much recursion"

### ISSUE THREAD

**Issue by theknigge** [kallookoo/wp-color-picker-alpha#29]
With WordPress theme like "Twenty Seventeen" (and some others), I got the problem that the customizer hangs while loading. In browser console an error is visible:

![2019-05-29 16_25_18-Entwicklerwerkzeuge - Customizer_ Lädt … - https___ds it93 de_wpress_wp-admin_cu](https://user-images.githubusercontent.com/29924160/58565176-8f8d0100-822e-11e9-8b6e-6b3dd8f6d7b5.png)

Seems that something is broken?
WordPress Version is 5.2.1

Thank you in advance for your help

**Comment by aristath** [comment]
@theknigge You can try using the modified version from https://github.com/WPTRT/control-color-alpha/blob/b79693ff53141e2a4aa8d204a1e82f2cfbcbadd8/src/wp-color-picker-alpha.js if you want, I just pushed some fixes there.

**Comment by kallookoo** [comment]
Hi @theknigge ,
The current version is 2.1.4  and the modified version of the @aristath is some and not work in.
Contact with the plugin author to upgrade the version.
