### ISSUE TITLE
Color Selector Misplacement on RTL pages

### ISSUE THREAD

**Issue by bugfloyd** [kallookoo/wp-color-picker-alpha#30]
First of all thanks for your great work.
There is a glitch in color selector button on RTL pages (e.g. RTL WP setups) that unfortunately causes to have two color layers seperated so we have no transparent preview on selector button and instead there are 2 squares, one empty and one with non-alpha color.

My simple solution was to use this CSS code:
`html[dir=rtl] .color-alpha {
    left: unset!important;
    right: 0!important;
}`

P.S. Since the style of that element implemented by JS, using this CSS code in an external CSS file may not work, I suggest using it as inline within HTML code after `</form>`.

**Comment by kallookoo** [comment]
I will try what you say, it is the first news I have about it.
I edit the title as it may not be a bug.

**Comment by kallookoo** [comment]
Resolved.
Thank you @bugfloyd
