### ISSUE TITLE
color-alpha span height is too short in WordPress 5.3

### ISSUE THREAD

**Issue by webaware** [kallookoo/wp-color-picker-alpha#31]
WordPress 5.3 changes some admin styling for improved accessibility. In WP 5.3, the color-alpha span is now too short -- 24px in a 26px hole -- and the transparent background cross-hatch shows through at the bottom of the span. PR coming.

**Comment by theDanielJLewis** [comment]
I see this in my WordPress as well.

**Comment by neilgee** [comment]
I see this too - but should be 28px

![Screen Shot 2020-03-19 at 1 47 39 pm](https://user-images.githubusercontent.com/2056045/77026877-d8de5500-69e8-11ea-989d-60c10b11e6c8.png)

**Comment by neilgee** [comment]
Oh I see you set the fix to 100%, good stuff

**Comment by kallookoo** [comment]
Update all files for this change
Thanks @webaware
