### ISSUE TITLE
Iris Alpha Slider not aligning properly (in Firefox)

### ISSUE THREAD

**Issue by maddisondesigns** [kallookoo/wp-color-picker-alpha#36]
Hi,

First up, thanks heaps for your work on adding alpha color to this WP Color Picker 🙏

An issue that has just started happening in the last week is that the Alpha Color Slider is no longer sitting properly within the control.

<img width="487" alt="screenshot_451" src="https://user-images.githubusercontent.com/2078245/89285631-12f87c80-d694-11ea-9afb-01a37c996964.png">

My Customizer controls were displaying fine last week and I haven't made any code changes in that time, but I have updated Firefox (macOS) to the latest version (79.0), so I think it's related to that. The control displays fine in Chrome and Safari.

I'm actually wondering if it's partly a Firefox bug. The `.iris-alpha-slider` element width appears to be rounding to 17.6333px wide even though the element is only set to 17.625px. When I view it in Chrome, the element width is rounded to 17.63 as expected.

<img width="1299" alt="screenshot_452" src="https://user-images.githubusercontent.com/2078245/89286454-95ce0700-d695-11ea-9b9e-75203bff3e25.png">

If I manually override the width of that Alpha slider in my Customizer css using the following style, the alpha slider goes back to displaying correctly.

```
.iris-picker-inner .iris-alpha-slider {
	width: 17.6px !important;
}
```

Using the above css, the alpha slider displays as expected:

<img width="1280" alt="screenshot_454" src="https://user-images.githubusercontent.com/2078245/89287550-8b147180-d697-11ea-923c-cfea8ac7d5ac.png">

**Comment by neilgee** [comment]
Yes - also seeing this in Firefox 79 & Firefox Developer 80

<img width="686" alt="Screen Shot 2020-08-05 at 9 40 00 am" src="https://user-images.githubusercontent.com/2056045/89355879-d1052000-d6ff-11ea-902a-ceee9c4d478c.png">

**Comment by webaware** [comment]
I reckon this is likely a Firefox bug. Here's a quick workaround for the script itself.

On [line 378](https://github.com/kallookoo/wp-color-picker-alpha/blob/e5a6154676d3ae5f6ac35b3d54a0abaa17e3142d/src/wp-color-picker-alpha.js#L378), change this:

`stripsWidth  = ( ( emptyWidth / 2 ) - stripsMargin );`

to this:

`stripsWidth  = ( ( emptyWidth / 2 ) - stripsMargin ) - 1;`

Yes, it's a dirty hack, but it works :)

**Comment by kallookoo** [comment]
Hi,
Try the branch 3.0.0 and comment please.

**Comment by kallookoo** [comment]
Resolved.
