### ISSUE TITLE
Version 3 not showing Color Picker

### ISSUE THREAD

**Issue by neilgee** [kallookoo/wp-color-picker-alpha#44]
I have been using wp-color-picker-alpha for various WordPress plugins settings, enqueuing the script and using like so...

```
function my_overlay_callback() {
$options = get_option( 'plugin_settings' );

if( !isset( $options['my_overlay'] ) ) $options['my_overlay'] = 'rgba(0,0,0,0.85)';

echo '<input type="text" class="color-picker" data-alpha="true" data-default-color="rgba(0,0,0,0.85)" name="plugin_settings[my_overlay]" value="' . sanitize_text_field($options['my_overlay']) . '"/>';
}
```

This gives me the color picker when selected.

![wordpress-default-rgba-color](https://user-images.githubusercontent.com/2056045/99728198-2cbbb380-2b0d-11eb-8b80-15dadc8e7a96.png)

Since version 3 of the script the picker no longer shows - it  just falls back to a text field for manual entry.

![Screen Shot 2020-11-20 at 8 49 45 am](https://user-images.githubusercontent.com/2056045/99728368-75736c80-2b0d-11eb-9c58-14160d3b31a9.png)

**Comment by kallookoo** [comment]
Hi @neilgee 
Read the [Usage](https://github.com/kallookoo/wp-color-picker-alpha#usage)
Now it is necessary to call it explicitly and I recommend using your own class to prevent other plugins or themes from modifying yours.

**Comment by neilgee** [comment]
Ok thanks, I have added `data-alpha-enabled="true"` to the input but picker still not displaying - I think its the inline script tripping me up, will look a bit more closely later.

**Comment by neilgee** [comment]
Have it sorted now - I already had a js file for the backend settings added `$( ".color-picker" ).wpColorPicker();` to it, now works perfect - thanks
