### ISSUE TITLE
There's still some deprecated jQuery

### ISSUE THREAD

**Issue by pacmanito** [kallookoo/wp-color-picker-alpha#46]
Hi, deprecated jQuery.fn.click() event shorthand is used in the script for a few times, e.g. here:

https://github.com/kallookoo/wp-color-picker-alpha/blob/b83cdb3063efb897c91ca8e80dd582afbdadb394/src/wp-color-picker-alpha.js#L570

and here:

https://github.com/kallookoo/wp-color-picker-alpha/blob/b83cdb3063efb897c91ca8e80dd582afbdadb394/src/wp-color-picker-alpha.js#L614

**Comment by kallookoo** [comment]
Thanks @pacmanito !!!

**Comment by pacmanito** [comment]
@kallookoo thanks for reacting that fast!
