### ISSUE TITLE
Conflict with Tutor LMS & User Activity Log plugin

### ISSUE THREAD

**Issue by parmarhardip** [kallookoo/wp-color-picker-alpha#48]
<img width="316" alt="image" src="https://github.com/kallookoo/wp-color-picker-alpha/assets/23077242/7f341cf8-a004-4dc9-a7f0-e7f0d476d72b">

<img width="1578" alt="image" src="https://github.com/kallookoo/wp-color-picker-alpha/assets/23077242/6b4a2828-c044-4025-84ab-9f2388eea71a">
<img width="1542" alt="image" src="https://github.com/kallookoo/wp-color-picker-alpha/assets/23077242/4845558f-8785-4a7a-92ce-5084b38e796b">

plugin links:
https://wordpress.org/plugins/tutor/
https://wordpress.org/plugins/user-activity-log/

**Comment by kallookoo** [comment]
Hi,
What are the WordPress versions and plugins?

**Comment by parmarhardip** [comment]
I have fixed the issue from our plugin.

I have loaded `wp-color-picker-alpha.js` in footer.

I was using the latest WordPress 6.2.2 and Tutor LMS 2.2.2 and User Activity Log 1.6.3

Thanks for the quick response.
