### ISSUE TITLE
Cannot Manually Type Color Code

### ISSUE THREAD

**Issue by katm-ndm** [kallookoo/wp-color-picker-alpha#52]
When typing into a colorfield after the third character is typed the rest of the color is automatically filled in to a color that was not chosen. I believe this may be due to the `_addInputListeners: function.`

I noticed that other functions do a check for alphaEnabled being true before running the logic, but the event listener `input.on( 'change', callback );` is being called despite alphaEnabled being false. 

For additional context: this issue is being experienced on Wordpress Admin edit page on Google Chrome.

Thank you for your work on this!

**Comment by kallookoo** [comment]
By default this is how it works and you should comment it out in its [repository](https://github.com/Automattic/Iris/issues) as this script does not modify it as it is not related to the alpha channel.
