### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '_super')

### ISSUE THREAD

**Issue by Regnalf** [kallookoo/wp-color-picker-alpha#53]
I get the following error when I try to use the script:

![screenshot_ 2024-06-24 um 21 41 45](https://github.com/kallookoo/wp-color-picker-alpha/assets/43412166/1b7ff3d0-d901-44d1-8864-78a2edd1e13f)

The field is converted into a colour selection field, but no colour selection window opens when you click on it.

**Comment by Regnalf** [comment]
And it seems not to work with multiple color fields!

**Comment by hakito** [comment]
Shouldn't this line

https://github.com/kallookoo/wp-color-picker-alpha/blob/399e2d9c107e27cf5c3937c960cd1d9b356465f3/src/wp-color-picker-alpha.js#L271

be 

```js
this._super();
```

**Comment by wildoperation** [comment]
> Shouldn't this line
> 
> https://github.com/kallookoo/wp-color-picker-alpha/blob/399e2d9c107e27cf5c3937c960cd1d9b356465f3/src/wp-color-picker-alpha.js#L271
> 
> be
> 
> ```js
> this._super();
> ```

This fixed the error for me and the picker appears to work as expected now.

Thanks!

**Comment by kallookoo** [comment]
It was corrected in version 3.0.4
