### ISSUE TITLE
Uncaught TypeError: Cannot read property 'wpColorPicker' of undefined(anonymous function)

### ISSUE THREAD

**Issue by elliotrock** [kallookoo/wp-color-picker-alpha#6]
Chrome error is:

Uncaught TypeError: Cannot read property 'wpColorPicker' of undefined(anonymous function) @ wp-color-picker-alpha.min.js?ver=4.3.1:2(anonymous function) @ wp-color-picker-alpha.min.js?ver=4.3.1:2
load-scripts.php?c=1&load[]=underscore,customize-base,wp-a11y,customize-controls,jquery-ui-sortable…:9 Uncaught TypeError: b.val(...).wpColorPicker is not a functione.ColorControl.e.Control.extend.ready @ load-scripts.php?c=1&load[]=underscore,customize-base,wp-a11y,customize-controls,jquery-ui-sortable…:9(anonymous function) @ load-scripts.php?c=1&load[]=underscore,customize-base,wp-a11y,customize-controls,jquery-ui-sortable…:9j @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mo…:2k.add @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mo…:2e.Control.e.Class.extend.initialize @ load-scripts.php?c=1&load[]=underscore,customize-base,wp-a11y,customize-controls,jquery-ui-sortable…:9e.Class @ load-scripts.php?c=1&load[]=underscore,customize-base,wp-a11y,customize-controls,jquery-ui-sortable…:7f @ load-scripts.php?c=1&load[]=underscore,customize-base,wp-a11y,customize-controls,jquery-ui-sortable…:7f @ load-scripts.php?c=1&load[]=underscore,customize-base,wp-a11y,customize-controls,jquery-ui-sortable…:7(anonymous function) @ load-scripts.php?c=1&load[]=underscore,customize-base,wp-a11y,customize-controls,jquery-ui-sortable…:10m.extend.each @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mo…:2(anonymous function) @ load-scripts.php?c=1&load[]=underscore,customize-base,wp-a11y,customize-controls,jquery-ui-sortable…:10j @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mo…:2k.fireWith @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mo…:2m.extend.ready @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mo…:2J @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mo…:2

I have updated to the most recent version of this.

Please help, thanks.

Elliot

**Comment by kallookoo** [comment]
Close, if external error

**Comment by bdalina54** [comment]
Having same issues
