### ISSUE TITLE
"Current Color" string is ignored ( wpColorPickerL10n.current ). Data attribute is missing.

### ISSUE THREAD

**Issue by MichaelWeb** [kallookoo/wp-color-picker-alpha#7]
https://github.com/23r9i0/wp-color-picker-alpha/blob/master/src/wp-color-picker-alpha.js#L62

To fix this issue replace :

self.toggler         = $( _before ).insertBefore( el ).css( { backgroundColor : self.initialValue } ).attr( 'title', wpColorPickerL10n.pick )**.data( 'current', wpColorPickerL10n.current )**;

with:

self.toggler = $( _before ).insertBefore( el ).css( { backgroundColor: self.initialValue } ).attr( 'title', wpColorPickerL10n.pick )**.attr( 'data-current', wpColorPickerL10n.current )**;

**Comment by kallookoo** [comment]
Update code, thanks!!!
