### ISSUE TITLE
Alpha slider doesn't change when color is set with javascript

### ISSUE THREAD

**Issue by TheoL** [kallookoo/wp-color-picker-alpha#9]
Hello, 

I am using something like:

`$('#my-color-picker').iris('color', 'rgba(100,100,100,0.25)');`

to change the color of the color-picker when some event happens.

The color is set correctly, but the alpha slider stays at 100%. (the alpha slider jumps to the correct position if I click anywhere inside the color picker, e.g. change the color)

**Comment by dbo90** [comment]
+1 for this one, the alpha slider doesn't update when we change the colorpicker via Javascript

**Comment by dbo90** [comment]
@TheoL a quick workaround I found is the following:

open the wp-color-picker-alpha.js file and find this:

```
_change: function() {
        this._super();
```

then replace it for this:

```
_change: function() {
        this._super();
        this._initControls();
```

**Comment by kallookoo** [comment]
ok, I'll see what I can do, in the new version

**Comment by kallookoo** [comment]
Hi,
Try the branch 3.0.0 and comment please.

**Comment by kallookoo** [comment]
Checked and changes perfectly.
Using `wpColorPicker( 'color', 'value' )` and `iris( 'color', 'value' )`.
